[package]
name = "tracing-layer-win-eventlog"
version = "1.0.0"
edition = "2021"
author = ["itsscb <dev@itsscb.de>"]
description = "Layer for the tracing_subscriber to write to the Windows EventLog"
keywords = ["tracing", "tracing_subscriber","layer","eventlog","windows"]
license = "MIT"
repository = "https://github.com/itsscb/tracing-layer-win-eventlog"
categories =["os::windows-apis"]

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Security",
    "Win32_System_EventLog"
]

[dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
windows-result = "0.3"